[tool.poetry]
name = "AndyRiddle_brain_games"
version = "0.1.0"
description = ""
authors = ["Andy <kas2850.cuk@yandex.ru>"]
packages = [
  { include = "brain_games" },
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
brain_games = "brain_games.scripts.brain_games:main"
